# Generated by Django 3.2.7 on 2022-01-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220122_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
