# Generated by Django 3.2.7 on 2022-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(blank=True, null=True, verbose_name='просмотры '),
        ),
    ]
