# Generated by Django 3.2.7 on 2022-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='просмотры '),
        ),
    ]
