# Generated by Django 3.2.7 on 2022-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
    ]
