# Generated by Django 3.2.7 on 2022-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220204_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='news.Ip'),
        ),
    ]
