# Generated by Django 3.2.7 on 2022-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220204_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='key_word',
            field=models.ManyToManyField(blank=True, to='news.Key_word'),
        ),
    ]
