# Generated by Django 3.2.7 on 2022-02-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220207_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key_word',
            options={'verbose_name': 'ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
    ]
