# Generated by Django 3.2.7 on 2022-02-16 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
