# Generated by Django 3.2.7 on 2022-02-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_account_created_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
