# Generated by Django 3.2.7 on 2022-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_rename_created_ad_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
