# Generated by Django 3.2.6 on 2021-08-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_text_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_2',
        ),
    ]
